version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/blog
    branches:
      only: master
    steps:
      - deploy:
          name: deploy to product
          command: |
            if [ "${CIRCLE_BRANCH}" == "master"  ]; then
              scp -oStrictHostKeyChecking=no -r . ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}
            fi
