version: 2

jobs:
  build:
    branches:
      only: master
    steps:
      - deploy:
          name: deploy to product
          command: |
            if [ "${CIRCLE_BRANCH}" == "master"  ]; then
              scp -r . ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}
            fi
